SECOND CLASS' PYTHON

exercice 3 question 1

In [ ]:
age=int(input('entrez votre age :'))
print(f" votre age est de ,age")

In [ ]:
if age <0 :
   print('age inexistant')
elif age < 6 :
    print('pupil')
elif age==6 or age==7 :
    print('minimal')
else :
    print('get married')

In [ ]:
for i in range(6):
    print(i, end='')

In [ ]:
chaine=input('entrez votre mot:')
caractere=input('entrez la lettre  recherchée:')
cpt=0
for i in chaine:
    if caractere==i:
        cpt=cpt+1
print('le nombre d''occurence est',cpt)

In [ ]:
def occurance(chaine,caractere):
    s=0
    for i in chaine:
        if caractere==i:
            s=+1
    return s


In [ ]:
def Compte_occurences(s):
    die={ }
    for mot in s.split():
        if mot in die:
            die[mot] += 1
        else:
            die[mot] = 1
    return die
print(Compte_occurences(" la vie est belle c'est la vie"))

ecrivez une fonction qui retourne la somme des valeurs d'un dictionnaire fourni en argument en supposant que toutes les valeurs stockes dans ce dictionnaire soient numerique



In [ ]:
def sum_valeur(dic):
    s=0
    for l in dic :      #or for l in dic.values() : s=s + l
        s=s+dic[l]
    return s

dic={"a":1,"b":2,"c":3,"d":4,"e":5}
sum_valeur(dic)

In [ ]:
a=float(input("entrez votre valeur :"))
b=a**3
print("le cube de votre nombre est :",b)

In [ ]:
a=str(input("entrez votre  premier caractere :"))
b=str(input("entrez votre  deuxieme caractere :"))
c=a
a=b
b=c
print("le resultat est ",a,b)

In [ ]:
def de(n):
    return n*2 + 3

print(de(4))

In [ ]:
n=int(input("entrez une valeur entiere :"))
if n%2 ==0 :
    print("paire")
else :
    print("impaire")

In [ ]:
a=float(input("entrez une valeur reel :"))
b=float(input("entrez une valeur reel :"))
c=float(input("entrez une valeur reel :"))

if a ==0 :
    print("equation du premier degré")
else :
    d=b*b - 4*a*c
    if d > 0 :
        print("deux solutions reels")
        r1=(-b + (d)**(1/2))/(2*a)
        r2=(-b - (d)**(1/2))/(2*a)
        print("les solutions sont:",r1,r2)
    elif d==0 :
        r1= -b/2*a
        print("la solutions est:",r1)
    else :
        print("pas de solutions")




In [ ]:
import os

rep="C:\Donnée base de donnée_CM"
for fichier in os.listdir(rep) :
    print(fichier)

In [ ]:
#rep= "C:\Donnée base de donnée_CM"
#for fichier in os.listdir(rep):
nom_complet_fichier = os.path.join(rep,"Table Client.csv")
    #print(fichier)
print(nom_complet_fichier)

In [ ]:
import os

def trouver_type_fichier(rep1, extension):
    # On ajoute le point si l'utilisateur ne l'a pas mis
    ext = '.' + extension if not extension.startswith('.') else extension

    try:
        fichiers = os.listdir(rep1)
        trouve = False

        for nom_fichier in fichiers:
            if nom_fichier.endswith(ext):
                print(nom_fichier)
                trouve = True

        if not trouve:
            print(f"Pas de fichier de type {ext} dans le répertoire {rep1}")

    except FileNotFoundError:
        print("Le répertoire spécifié est introuvable.")

# Utilisation du préfixe 'r' pour le chemin Windows
trouver_type_fichier(r"C:\Donnée base de donnée_CM", "txt")


In [ ]:
chemin=r"C:\Program Files\Notepad++\fichier text.txt"
fp= open(chemin, "r", encoding="utf-8")
for ligne in fp.readlines():
    print(ligne)

In [ ]:
import csv
chemin=r"C:\Donnée base de donnée_CM\table PC.csv"
fp=open(chemin, "r", encoding="utf-8")
for ligne in csv.DictReader(fp,delimiter=';'):
    for cle,valeur in ligne.items() :
        print(cle,valeur)
    print('fin de ligne')

In [ ]:
chemin1=r"C:\fichier text.txt"
fp=open(chemin1, "a", encoding="utf-8", newline='\n')
fp.write( " the lab is going with relative ease")
fp.close()

fp= open(chemin1, "r", encoding="utf-8")
for ligne in fp.readlines():
    print(ligne)


In [ ]:
x= 3.9 + (4-3)
print("la valeur de x est ",x)
print("la valeur de x est {}".format(x))

In [ ]:
def termes_suite(rang, u_0=2): #le rang de la suite et le termes initial
    U = [0] * (rang + 1)
    U[0]=u_0
    print("la liste des indices de la suite plus petit que 1000 \n" )
    if rang==0 :
        print("U_0","=",U[0])
    else:
        print("U_0","=",U[0])
    for i in range (1,rang + 1) :
        U[i]= U[i-1]**2
        if U[i] <= 1000:
            print("U_",i,"=",U[i])


termes_suite(50)

In [ ]:
"exo 3.1 pages 22"
import datetime as dt

d1=dt.datetime(1920,1,2,7,32)
d2=dt.datetime(1920,3,4,5,53)
d3=d2-d1

d4=dt.datetime(1999,12,30,17,12)
d5=dt.datetime(2000,3,1,15,53)
d6=d5 - d4
print(d6 < d3 )


In [ ]:
"exo 3.2 pages 22"
y1=dt.datetime(2010,1,1)
y2=dt.datetime(2030,1,1)
d1=y1.year
d2=y2.year
for year in range(d1,d2 + 1):
    if (year%4 ==0) and (year%100 != 0):
        print("the year",year,"is bessextille")
    else :
        print ("the year", year," is not bissextille")


In [ ]:
#give the possibility to the user to pick up one of the format datetime
#this is a function to fetch a "date" within a sentence
import datetime as dt

def detectionDate(text, date_format):
    # Split the sentence into individual words
    words = text.split()

    for word in words:
        try:
            # Try to convert each word based on the user's format
            found_date = dt.datetime.strptime(word, date_format)
            return str(found_date.date())
        except :
            # If the word doesn't match the format, move to the next word
            continue

    return "Impossible to find a date matching that format."

# Example Usage:
print(detectionDate('i was born 2022/2/21', "%Y-%m-%d"))


In [6]:
"seance 16/04/2026"
import numpy as np
B= np.array([[15,1,19],[20,12,17],[10,2,3]])
print(B )

print("="*30)
print("Transposé")
print("="*30)

print(B.T) #transposée


[[15  1 19]
 [20 12 17]
 [10  2  3]]
Transposé
[[15 20 10]
 [ 1 12  2]
 [19 17  3]]


In [17]:
#produit matriciel
A=np.array([[4,5,6,7],[2,6,7,8]] )
B=np.array([[0,1,0,1],[1,1,1,2]])
AB=np.dot(A,B.T)   #le produit
print(AB)
print("="*30)
print(AB.shape) #la taile

[[12 29]
 [14 31]]
(2, 2)


In [32]:
A=np.array([[4,5,6,7],[2,6,7,8]] ,dtype=float)
B=np.array([[0,1,0,1],[1,1,1,2]] ,dtype=float)
AB = A@B.T
print(AB)
print(AB.shape)
print(AB[1,1])     #les matrices commencent a etre indexé a zero

[[12. 29.]
 [14. 31.]]
(2, 2)
31.0


In [22]:
A=np.linspace(1,10,5)
print(A)

[ 1.    3.25  5.5   7.75 10.  ]


In [49]:
"ecrire un programme python qui donne les informations d'une personnes"




class Personne :
    def __init__(self, nom,prenom,numero,fonction):
        self.nom=nom
        self.prenom = prenom
        self.numero = numero
        self.fonction = fonction
    def description(self):
        print(self.nom,'travaille comme ',self.fonction)
        print("son numero est" ,self.numero)

personne1=Personne('koffi','smith','0777677481','PDG')
personne1.description()


koffi travaille comme  PDG
son numero est 0777677481
